def pode_ter_habilitacao():
    try:
        idade = int(input("Qual a sua idade? "))
        antecedentes = int(input("Você tem antecedentes criminais? (1-sim/2-não) "))
        exame_teorico = int(input("Você passou no exame teórico? (1-sim/2-não) "))
        exame_pratico = int(input("Você passou no exame prático? (1-sim/2-não) "))
        if (idade >= 18 and antecedentes == 2 and exame_teorico == 1 and exame_pratico == 1):
            print("Você pode obter a habilitação!")
        else:
            print("Você não atende aos requisitos para obter a habilitação.")
    except ValueError:
        print("Por favor, insira uma idade válida.")

pode_ter_habilitacao()
